pipeline {
  agent any

  environment {
    ANSIBLE_CONFIG = "${WORKSPACE}/deploy/.ansible.cfg"
  }

  stages {
    stage('Clean Workspace') {
      steps {
        cleanWs()
      }
    }

    stage('Checkout SCM') {
      steps {
        echo "Checking out main branch..."
        git branch: 'main', url: 'https://github.com/princemaxi/ansible-config-mgt.git'
      }
    }

    stage('Validate Workspace') {
      steps {
        echo "Listing files to confirm structure..."
        sh 'pwd && ls -R'
      }
    }

    stage('Run Ansible Playbook') {
      steps {
        script {
          echo "Starting Ansible Deployment..."
          sh '''
            echo "Using ansible config at: $ANSIBLE_CONFIG"
            ansible-playbook -i inventory/dev.ini playbooks/site.yml
          '''
        }
      }
    }
  }

  post {
    always {
      echo "Pipeline completed!"
    }
  }
}

