pipeline {
  agent any

  environment {
    ANSIBLE_CONFIG = "${WORKSPACE}/deploy/.ansible.cfg"
  }

  stages {
    stage('Cleanup Workspace') {
      steps {
        script {
          echo "Cleaning up workspace..."
          // Clean safely without removing Jenkinsfile or .git
          sh 'find . -mindepth 1 ! -name ".git" ! -name "Jenkinsfile" -exec rm -rf {} + || true'
        }
      }
    }

    stage('Checkout SCM') {
      steps {
        echo "Checking out main branch..."
        git branch: 'main', url: 'https://github.com/princemaxi/ansible-config-mgt'
      }
    }

    stage('Run Ansible Playbook') {
      steps {
        script {
          echo "Starting Ansible Deployment..."
          sh '''
            ansible-config-mgt || exit 1
            ansible-playbook -i inventory/dev.ini playbooks/site.yml
          '''
        }
      }
    }
  }
}

